### ISSUE TITLE
CRAN: Description fixes

### ISSUE THREAD

**Issue by bcastanho** [bcastanho/SCtools#17]
Use single quotation marks for package names, software names and API names; describe the significance tests.

If there are references describing the (theoretical background of) 
methods in your package, please add these in the Description field of 
your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
with no space after 'doi:', 'arXiv:' and angle brackets for auto-linking.

**Comment by medewitt** [comment]
Resolved with #22 and #21
