### ISSUE TITLE
CRAN: Examples fixes

### ISSUE THREAD

**Issue by bcastanho** [bcastanho/SCtools#18]
unwrap the examples if that is feasible and if they can be 
executed in < 5 sec for each Rd file or create additionally small toy 
examples. Something like
\examples{
    examples for users and checks:
    executable in < 5 sec
    \dontshow{
        examples for checks:
        executable in < 5 sec together with the examples above
        not shown to users
    }
    donttest{
        further examples for users (not used for checks)
    }
    if(interactive()){
        interactive examples (not used for checks)
    }
}

**Comment by medewitt** [comment]
Resolved with #22 and #21
