### ISSUE TITLE
Error? on using plot_placebos

### ISSUE THREAD

**Issue by LungtaSEKI** [bcastanho/SCtools#26]
---

Hello, this is my first time to use SCtools but I am facing an issue when generating a placebo. The problem is that the color of control units and the treated unit on the placebo plot looks like reversed as you can see in the Rpolt attached. The control unit should be grey color. I would be extremely grateful if anybody gives me  the solution.

[SCNdf.csv](https://github.com/bcastanho/SCtools/files/8821995/SCNdf.csv)

```r
SCNdf <- read.csv("data/SCNdf.csv")

library(Synth)
library(SCtools)

dataprep.out <- dataprep(
  foo = SCNdf,
  predictors = "RC",
  special.predictors = list(
    list("PP",                    1995, "mean"),
    list("PP",                    2003, "mean"),
    list("HS",                    2007, "mean"),
    list("PS",            2005:2006, "mean"),
    list("PS",                     2010, "mean"),
    list("LD",                     2002, "mean"),
    list("Frac",                   2001, "mean"),
    list("avincome", 1993:2003, "mean")
  ),
  dependent = "PP",
  unit.variable = "unit.num",
  unit.names.variable = "Country",
  time.variable = "Year",
  treatment.identifier = 9,
  controls.identifier = unique(SCNdf$unit.num)[-9],
  time.predictors.prior = 1994:2003,
  time.optimize.ssr = 2004:2013,
  time.plot = 1993:2021)

synth.out <- synth(dataprep.out, Sigf.ipop=2)

tdf <- generate.placebos(dataprep.out,synth.out, Sigf.ipop = 2)

placebo <- generate.placebos(dataprep.out = dataprep.out,
                             synth.out = synth.out, 
                             strategy = "multiprocess")
plot_placebos(placebo)

```
![Rplot](https://user-images.githubusercontent.com/106731974/171586484-0aeb87ce-dc9b-423d-8ca5-76fbaff28206.png)

**Comment by bcastanho** [comment]
Thanks for flagging this! It was a bug in plot_placebos that I just fixed. You can download version 0.3.2.1 from github and it will work correctly. It'll be on CRAN shortly

**Comment by genlaurareich** [comment]
@bcastanho Hi. I am having the same issue and the vertical line also appears in the wrong spot even though i specified at what year it should appear. I downloaded version 0.3.2.1 from github and it still did not make a difference. Would you be able to provide more specific instructions on how to resolve this issue please?
